# Generated by Django 2.2.4 on 2019-08-08 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier_in_payment_option', models.CharField(choices=[('T0', 'TIER0'), ('T1', 'TIER1'), ('T2', 'TIER2'), ('T3', 'TIER3')], default='T0', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateTimeField(verbose_name='Transaction Date')),
                ('payment_cancellation', models.BooleanField(verbose_name='Payment Cancellation')),
                ('payment_tier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='payments.PaymentTier')),
            ],
        ),
        migrations.CreateModel(
            name='BillingInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_address', models.CharField(max_length=100, verbose_name='Delivery Address')),
                ('stripe_customer_id', models.CharField(max_length=100, verbose_name='Stripe Customer ID')),
                ('payment_tier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='payments.PaymentTier')),
            ],
        ),
    ]
