# Generated by Django 2.2.5 on 2019-09-13 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_auto_20190911_2225'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_1', models.CharField(max_length=500)),
                ('line_2', models.CharField(max_length=500, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100, null=True)),
                ('zip', models.CharField(max_length=100, null=True)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='billinginfo',
            name='delivery_address',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='payments.Address'),
        ),
    ]
