# Generated by Django 2.2.5 on 2019-09-17 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_auto_20190917_2257'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'get_latest_by': 'transaction_date'},
        ),
    ]
