import os

# NGROK
NGROK_HOST='95c0c850.ngrok.io'

# GOOGLE
GOOGLE_MAPS_PLACES = 'AIzaSyAStU9SHXwqw6iyBonOjkIQtzgQ8FguR3U'

# STRIPE
STRIPE_API_KEY = os.environ['STRIPE_API_KEY']
STRIPE_PUBLIC_KEY = os.environ['STRIPE_PUBLIC_KEY']
PULP_STRIPE_PLAN = os.environ['PULP_STRIPE_PLAN']

# AWS S3
S3_USER_ACCESS_ID = os.environ['AWS_ACCESS_KEY_ID']
S3_USER_SECRET = os.environ['AWS_SECRET_ACCESS_KEY']
PDF_BUCKET = os.environ['AWS_PDF_BUCKET']
HTML_BUCKET = os.environ['AWS_HTML_BUCKET']

# POCKET
POCKET_CONSUMER_KEY = os.environ['POCKET_CONSUMER_KEY']

# INSTAPAPER
INSTAPAPER_CONSUMER_ID = os.environ['INSTAPAPER_CONSUMER_ID']
INSTAPAPER_CONSUMER_SECRET = os.environ['INSTAPAPER_CONSUMER_SECRET']

