# Generated by Django 2.2.4 on 2019-08-08 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='billing_information',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.BillingInfo'),
        ),
    ]
