# Generated by Django 2.2.6 on 2019-11-11 04:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('title', models.CharField(max_length=255, verbose_name='Article Title')),
                ('permalink', models.URLField(max_length=500, primary_key=True, serialize=False, verbose_name='Permalink')),
                ('words', models.IntegerField(default=1, null=True, verbose_name='Number of Words')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Blog Name')),
                ('last_polled_time', models.DateTimeField(max_length=8, null=True, verbose_name='Last Polled Time')),
                ('home_url', models.URLField(verbose_name='Home URL')),
                ('rss_url', models.URLField(verbose_name='RSS URL')),
                ('scraped_old_posts', models.BooleanField(default=False, verbose_name='Scraped Old Posts')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_subscribed', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Subscribed')),
                ('blog', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blogs.Blog')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReadingListItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Added')),
                ('archived', models.NullBooleanField(verbose_name='Archived')),
                ('trashed', models.NullBooleanField(verbose_name='Trashed')),
                ('delivered', models.NullBooleanField(verbose_name='Delivered')),
                ('article', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='blogs.Article')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('reader', 'article')},
            },
        ),
    ]
