# Generated by Django 2.2.6 on 2019-11-11 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='excerpt',
            field=models.TextField(null=True, verbose_name='Excerpt'),
        ),
    ]
