# Generated by Django 2.2.4 on 2019-08-17 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_blog_scraped_old_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='last_polled_time',
            field=models.DateTimeField(max_length=8, null=True, verbose_name='Last Polled Time'),
        ),
    ]
