# Generated by Django 2.2.4 on 2019-08-17 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_auto_20190817_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_published',
            field=models.DateTimeField(verbose_name='Date Published'),
        ),
        migrations.AlterField(
            model_name='article',
            name='permalink',
            field=models.URLField(primary_key=True, serialize=False, verbose_name='Permalink'),
        ),
    ]
