# Generated by Django 2.2.3 on 2019-09-03 17:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_article_pdf_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='date_subscribed',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 3, 17, 6, 47, 27676, tzinfo=utc), verbose_name='Date Subscribed'),
        ),
    ]
