# Generated by Django 2.2.3 on 2019-09-07 00:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_auto_20190903_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='date_subscribed',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 7, 0, 47, 41, 561270, tzinfo=utc), verbose_name='Date Subscribed'),
        ),
    ]
