# Generated by Django 2.2.3 on 2019-09-11 22:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0011_auto_20190911_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='date_subscribed',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 11, 22, 24, 48, 502709, tzinfo=utc), verbose_name='Date Subscribed'),
        ),
    ]
