# Generated by Django 2.2.5 on 2019-09-21 05:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0019_auto_20190917_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='date_subscribed',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 21, 5, 32, 16, 351462, tzinfo=utc), verbose_name='Date Subscribed'),
        ),
    ]
