# Generated by Django 2.2.5 on 2019-10-07 00:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0023_auto_20191007_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='date_subscribed',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Subscribed'),
        ),
    ]
