# Generated by Django 2.2.6 on 2019-10-27 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogs', '0025_auto_20191016_0144'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingListItem',
            fields=[
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Added')),
                ('title', models.CharField(max_length=255, verbose_name='Article Title')),
                ('permalink', models.URLField(primary_key=True, serialize=False, verbose_name='Permalink')),
                ('date_published', models.DateTimeField(verbose_name='Date Published')),
                ('author', models.CharField(max_length=255, verbose_name='Author')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
