# Generated by Django 2.2.6 on 2019-10-28 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0026_readinglistitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readinglistitem',
            name='permalink',
        ),
        migrations.AddField(
            model_name='readinglistitem',
            name='link',
            field=models.URLField(default='', primary_key=True, serialize=False, verbose_name='Link'),
        ),
    ]
