# Generated by Django 2.2.6 on 2019-10-28 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0027_auto_20191028_0651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readinglistitem',
            name='author',
        ),
        migrations.RemoveField(
            model_name='readinglistitem',
            name='date_published',
        ),
        migrations.AlterField(
            model_name='readinglistitem',
            name='date_added',
            field=models.DateTimeField(verbose_name='Date Added'),
        ),
    ]
