# Generated by Django 2.2.6 on 2019-10-29 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0028_auto_20191028_0757'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-date_published']},
        ),
        migrations.AddField(
            model_name='readinglistitem',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Archived'),
        ),
        migrations.AddField(
            model_name='readinglistitem',
            name='trashed',
            field=models.BooleanField(default=False, verbose_name='Trashed'),
        ),
    ]
