# Generated by Django 2.2.6 on 2019-10-29 16:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogs', '0029_auto_20191029_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='readinglistitem',
            name='delivered',
            field=models.BooleanField(default=False, verbose_name='Delivered'),
        ),
        migrations.AlterField(
            model_name='readinglistitem',
            name='link',
            field=models.URLField(default='', verbose_name='Link'),
        ),
        migrations.AddField(
            model_name='readinglistitem',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='readinglistitem',
            unique_together={('reader', 'link')},
        ),
    ]
