version: '3.7'

services:
  frontend:
    build: ./frontend
    volumes:
      - ./frontend/pulp/src/:/app/src
    ports:
      - 8080:8080
    environment:
      - NODE_ENV=development
  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
  redis:
    image: redis:5.0.6-alpine
    command: redis-server
    expose:
      - "6379"
  db:
    image: postgres:12.0-alpine
    ports:
      - 5432:5432
    volumes:
      - /tmp/postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=paperweb
      - POSTGRES_DB=pulp_db
  node:
    build: ./node
    command: npm run dev
    volumes:
      - ./node:/usr/src/app/
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
