version: '3.7'

services:
  frontend:
    build: ./frontend
    ports:
      - 8080:8080
    environment:
      - NODE_ENV=development
  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=paperweb
      - POSTGRES_DB=pulp_db

volumes:
  postgres_data:
