# Generated by Django 2.2.4 on 2019-08-13 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20190813_0406'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='scraped_old_posts',
            field=models.BooleanField(default=False, verbose_name='Scraped Old Posts'),
        ),
    ]
