# Generated by Django 2.2.3 on 2019-08-29 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_auto_20190829_0304'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pdf_link',
            field=models.URLField(default=None, null=True, verbose_name='S3 PDF Link'),
        ),
    ]
