# Generated by Django 2.2.3 on 2019-09-07 00:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_auto_20190907_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='date_subscribed',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 7, 0, 49, 23, 713695, tzinfo=utc), verbose_name='Date Subscribed'),
        ),
    ]
