# Generated by Django 2.2.5 on 2019-09-15 22:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0014_auto_20190913_0445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='date_subscribed',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 15, 22, 55, 40, 814395, tzinfo=utc), verbose_name='Date Subscribed'),
        ),
    ]
