# Generated by Django 2.2.5 on 2019-10-07 00:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0022_auto_20191007_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='date_subscribed',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 7, 0, 56, 54, 65612, tzinfo=utc), verbose_name='Date Subscribed'),
        ),
    ]
