apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    tier: backend
  name: pulp-backend-config
data:
  DJANGO_SETTINGS_MODULE: pulp.prod_settings
  ALLOWED_HOSTS: "*"
  SQL_ENGINE: django.db.backends.postgresql
  SQL_HOST: pulp-postgres-db-service
  SQL_PORT: "5432"
  SQL_DATABASE: "pulp_db"
  BACKEND_PORT: "8000"
  PARSER_HOST: pulp-parser-service
  PUPPETEER_HOST: pulp-puppeteer-service
  PARSER_PORT: "3000"
  REDIS_HOST: pulp-redis-service 
  REDIS_PORT: "6379"
  SESSION_COOKIE_SECURE: "True"
  CSRF_COOKIE_SECURE: "True"
  SECURE_SSL_REDIRECT: "True"
  STATICFILES_STORAGE: "whitenoise.storage.CompressedStaticFilesStorage"
  SILENCED_SYSTEM_CHECKS: "captcha.recaptcha_test_key_error"
  AWS_HTML_BUCKET: "pulphtml-test"
  AWS_PDF_BUCKET: "pulppdf-test"
  FRONTEND_HOST: "/static/js/build/"
  EMAIL_HOST_USER: "rahul@getpulp.io"
  ACCOUNT_EMAIL_VERIFICATION: "optional"
  SITE_ID: "1"
  ACCOUNT_CONFIRM_EMAIL_ON_GET: "True"
  HEALTHCHECK_CELERY_TIMEOUT: "15"