apiVersion: v1
kind: Service
metadata:
  name: pulp-daphne-service
  labels:
    component: pulp-daphne-service
    pulp.service: pulp-daphne
    tier: backend
spec:
  type: NodePort
  ports:
  - name: "daphne-port"
    port: 8001
    targetPort: 8001
  selector:
    component: pulp-daphne-pod
    pulp.service: pulp-daphne
    tier: backend
status:
  loadBalancer: {}