apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pulp-daphne-deployment
  labels:
    component: pulp-daphne-pod
    pulp.service: pulp-daphne
    tier: backend
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      component: pulp-daphne-pod
  template:
    metadata:
      labels:
        component: pulp-daphne-pod
        pulp.service: pulp-daphne
        tier: backend
    spec:
      containers:
      - name: pulp-daphne
        image: gcr.io/prod1-259305/pulp-backend:v1
        command: ['daphne', '-b', '0.0.0.0', '-p', '8001', 'pulp.asgi:channel_layer',
                  '&&', 'python', 'manage.py', 'runworker']
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: pulp-backend-config
          - secretRef:
              name: pulp-backend-credentials
        env:
        - name: SQL_USER
          valueFrom:
            secretKeyRef:
               name: pulp-postgres-db-credentials
               key: user
        - name: SQL_PASSWORD
          valueFrom:
            secretKeyRef:
               name: pulp-postgres-db-credentials
               key: password
        livenessProbe:
          httpGet:
            path: ready/
            port: 8001
          initialDelaySeconds: 30
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: ready/
            port: 8001
          initialDelaySeconds: 15
          periodSeconds: 20
          timeoutSeconds: 10
          successThreshold: 1
          failureThreshold: 2
        ports:
          - containerPort: 8001
        resources: {}
      restartPolicy: Always
status: {}
