apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-claim-volume
  labels:
    pulp.service: db-claim
spec:
  storageClassName: standard
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
