apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frontend-claim-volume
  labels:
    pulp.service: frontend-claim
spec:
  storageClassName: standard
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}

