apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    pulp.service: frontend
  name: frontend
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        pulp.service: frontend
    spec:
      containers:
      - env:
        - name: NODE_ENV
          value: development
        image: gcr.io/sandbox-164917/pulp-frontend:v1
        imagePullPolicy: Always
        name: frontend
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
