apiVersion: v1
kind: Service
metadata:
  name: pulp-parser-service
  labels:
    component: pulp-parser-service
    pulp.service: pulp-parser
    tier: backend
spec:
  ports:
  - name: "parser-port"
    port: 3000
    targetPort: 3000 
  selector:
    component: pulp-parser-pod
    pulp.service: pulp-parser
    tier: backend
status:
  loadBalancer: {}
