apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pulp-parser-deployment
  labels:
    component: pulp-parser-pod
    pulp.service: pulp-parser
    tier: backend 
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      component: pulp-parser-pod
  template:
    metadata:
      labels:
        component: pulp-parser-pod
        pulp.service: pulp-parser
        tier: backend 
    spec:
      containers:
      - name: pulp-parser
        args:
        - npm
        - run
        - dev
        image: gcr.io/prod1-259305/pulp-parser:v1
        imagePullPolicy: Always
        env:
        - name: PARSER_HOST 
          valueFrom:
            configMapKeyRef:
              key: PARSER_HOST 
              name: pulp-backend-config
        - name: PARSER_PORT
          valueFrom:
            configMapKeyRef:
              key: PARSER_PORT
              name: pulp-backend-config
        ports:
        - containerPort: 3000
        resources: {}
      restartPolicy: Always
status: {}
