FROM node:12.2.0-alpine
RUN apk update && apk upgrade && apk add --no-cache bash git openssh
WORKDIR /usr/src/app
COPY ./package*.json .
RUN npm install --silent
COPY . .
ARG PARSER_PORT=3000
EXPOSE ${PARSER_PORT}
USER node
CMD [ "npm", "run", "start" ]
