# Generated by Django 2.2.7 on 2020-04-23 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twittercredentials',
            name='name',
        ),
        migrations.RemoveField(
            model_name='twittercredentials',
            name='twitter_id',
        ),
    ]
