# Generated by Django 2.2.7 on 2020-04-23 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0002_auto_20200423_0553'),
    ]

    operations = [
        migrations.AddField(
            model_name='twittercredentials',
            name='since_id',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
    ]
