# Generated by Django 2.2.7 on 2020-04-23 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0003_twittercredentials_since_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('twitter_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=500)),
                ('reply_to', models.CharField(default=None, max_length=64, null=True)),
                ('quote', models.CharField(default=None, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TweetLink',
            fields=[
                ('url', models.URLField(primary_key=True, serialize=False)),
                ('tco_url', models.URLField(default=None, null=True)),
                ('tweet_parent', models.ForeignKey(db_column='tweet_parent', on_delete=django.db.models.deletion.CASCADE, to='twitter.Tweet')),
            ],
        ),
    ]
