# Generated by Django 2.2.7 on 2020-04-24 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reading_list', '0007_article_blog'),
        ('twitter', '0004_tweet_tweetlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetlink',
            name='article',
            field=models.ForeignKey(db_column='tweetlink_article', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='reading_list.Article'),
        ),
    ]
