# Generated by Django 2.2.3 on 2019-09-11 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_billinginfo_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billinginfo',
            name='delivery_address',
            field=models.CharField(default=None, max_length=100, verbose_name='Delivery Address'),
        ),
        migrations.AlterField(
            model_name='billinginfo',
            name='payment_tier',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='payments.PaymentTier'),
        ),
        migrations.AlterField(
            model_name='billinginfo',
            name='stripe_customer_id',
            field=models.CharField(default=None, max_length=100, verbose_name='Stripe Customer ID'),
        ),
    ]
