# Generated by Django 2.2.5 on 2019-09-15 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_auto_20190913_0445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billinginfo',
            name='delivery_address',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.Address'),
        ),
    ]
