# Generated by Django 2.2.5 on 2019-09-21 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_auto_20190917_2307'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
