apiVersion: "extensions/v1beta1"
kind: "Ingress"
metadata:
  name: "pulp-ingress"
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "web-static-ip"
    networking.gke.io/managed-certificates: "pulp-certificate"
  namespace: "default"
spec:
  rules:
  - http:
      paths:
      - path: /*
        backend:
          serviceName: pulp-backend-service
          servicePort: 8000
      - path: /ws/*
        backend:
          serviceName: pulp-daphne-service
          servicePort: 8001