FROM python:3.7.4-alpine

RUN adduser -D printer_start

WORKDIR /home/printer_start

COPY ./requirements.txt requirements.txt
RUN pip install -r requirements.txt
RUN pip install gunicorn

COPY app app
COPY printer_start.py config.py boot.sh ./
RUN chmod +x boot.sh

ENV FLASK_APP printer_start.py

RUN chown -R printer_start:printer_start ./
USER printer_start

EXPOSE 5000
ENTRYPOINT ["./boot.sh"]