apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    tier: backend
  name: pulp-backend-config
data:
  DJANGO_SETTINGS_MODULE: pulp.prod_settings
  SECRET_KEY: '*-4q4au)57$4tz-s@mlt8mm!-ibju'
  SQL_ENGINE: django.db.backends.postgresql
  SQL_HOST: pulp-postgres-db-service
  SQL_PORT: "5432"
  SQL_DATABASE: pulp_db
  RECAPTCHA_PUBLIC_KEY: 6LdhB8QUAAAAADsIgnDJ2HR4FyNm8MM1q1Xxw9_F
  RECAPTCHA_PRIVATE_KEY: 6LdhB8QUAAAAAKJPN5j7tYFTohKxjQJ0_gdFt6wB
  EMAIL_HOST_PASSWORD: TiYDvGJwsjnZB7eXmxJQUJcG
