NGROK_HOST = 'edb661da.ngrok.io'

GOOGLE_MAPS_PLACES = 'AIzaSyAStU9SHXwqw6iyBonOjkIQtzgQ8FguR3U'
STRIPE_API_KEY = 'sk_test_gZ50gEoA6E8vcDZC3IZVyVqi00e5FInywM'
STRIPE_PUBLIC_KEY = 'pk_test_9DUWDnI9T5YJWmLRhNn6nHtS'

PULP_STRIPE_PLAN = 'plan_FpKS1u80kRynhr'