# NGROK
NGROK_HOST = '95c0c850.ngrok.io'

# GOOGLE
GOOGLE_MAPS_PLACES = 'AIzaSyAStU9SHXwqw6iyBonOjkIQtzgQ8FguR3U'

# STRIPE
STRIPE_API_KEY = 'sk_test_gZ50gEoA6E8vcDZC3IZVyVqi00e5FInywM'
STRIPE_PUBLIC_KEY = 'pk_test_9DUWDnI9T5YJWmLRhNn6nHtS'
PULP_STRIPE_PLAN = 'plan_FpKS1u80kRynhr'

# AWS S3
S3_USER_ACCESS_ID = 'AKIARZQDMPCHBIOKQGLU'
S3_USER_SECRET = '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'
