# Generated by Django 2.2.3 on 2019-09-11 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190808_0533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='billing_information',
        ),
    ]
