apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pulp-postgres-db-volume-claim
  labels:
    component: pulp-postgres-db-volume-claim
    pulp.service: pulp-postgres-db
    tier: database
spec:
  storageClassName: standard
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
