apiVersion: v1
kind: Service
metadata:
  name: pulp-postgres-db-service
  labels:
    component: pulp-postgres-db-service
    pulp.service: pulp-postgres-db
    tier: postgres-db
spec:
  ports:
   - port: 5432
     targetPort: 5432
  selector:
    component: pulp-postgres-db-pod
    pulp.service: pulp-postgres-db
    tier: database
