apiVersion: v1
kind: Service
metadata:
  name: pulp-celery-service
  labels:
    component: pulp-celery-service
    pulp.service: pulp-celery
    tier: backend
spec:
  selector:
    component: pulp-celery-pod
    pulp.service: pulp-celery
    tier: backend
status:
  loadBalancer: {}
