apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pulp-celery-deployment
  labels:
    component: pulp-celery-pod
    pulp.service: pulp-celery
    tier: backend
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      component: pulp-celery-pod
  template:
    metadata:
      labels:
        component: pulp-celery-pod
        pulp.service: pulp-celery
        tier: backend
    spec:
      containers:
      - name: pulp-celery
        image: gcr.io/sandbox-164917/pulp-celery:v1
        imagePullPolicy: Always
        env:
        - name: SQL_USER
          valueFrom:
            secretKeyRef:
               name: pulp-postgres-db-credentials
               key: user
        - name: SQL_PASSWORD
          valueFrom:
            secretKeyRef:
               name: pulp-postgres-db-credentials
               key: password
          initialDelaySeconds: 15
          periodSeconds: 20
          timeoutSeconds: 10
          successThreshold: 1
          failureThreshold: 2
        resources: {}
      restartPolicy: Always
status: {}
